### ISSUE TITLE
Add info about Good First Issues on GitHub

### ISSUE THREAD

**Issue by tiferet** [github/opensource.guide#1052] opened 2019-08-09 20:07 UTC
Good First Issues is a new feature that recently shipped on GitHub. It helps people contribute to open source by recommending beginner-friendly issues that fit their interests. 

These recommendations are surfaced on [Topics pages](https://github.com/topics/javascript), on [/discover](https://github.com/discover) (and soon also on [/explore](https://github.com/explore) and [/trending](https://github.com/trending)), and in specific repos' [/contribute pages](https://github.com/prettier/prettier/contribute).

I think it would be useful to share this information both with maintainers and with users looking to start contributing, by adding it to this guide. We could:

- Tell potential contributors how to use this feature to find a beginner-friendly issue in [How to Contribute](https://opensource.guide/how-to-contribute/).
- Tell maintainers how to leverage this feature to draw and onboard new users either in [Building Welcoming Communities](https://opensource.guide/building-community/), or in [Best Practices for Maintainers](https://opensource.guide/best-practices/) 🤷‍♀ 

_Note:_ If maintainers find that their good first issues are not being surfaced, they can add the label "good first issue", "beginner friendly", or the like. If they have a similar label they are already using that is not being surfaced, they can contact us and we can add it to the list of synonymous labels. There can be a 24 hour lag for the data to refresh.

I am happy to help out on this in any way possible.

Thank you!

**Comment by AAMetatron** [comment] 2019-08-13 07:57
its all good its bad but don't worry its good

**Comment by aliceap** [comment] 2019-08-21 14:36
> Good First Issues is a new feature that recently shipped on GitHub. It helps people contribute to open source by recommending beginner-friendly issues that fit their interests.
> 
> These recommendations are surfaced on [Topics pages](https://github.com/topics/javascript), on [/discover](https://github.com/discover) (and soon also on [/explore](https://github.com/explore) and [/trending](https://github.com/trending)), and in specific repos' [/contribute pages](https://github.com/prettier/prettier/contribute).
> 
> I think it would be useful to share this information both with maintainers and with users looking to start contributing, by adding it to this guide. We could:
> 
> * Tell potential contributors how to use this feature to find a beginner-friendly issue in [How to Contribute](https://opensource.guide/how-to-contribute/).
> * Tell maintainers how to leverage this feature to draw and onboard new users either in [Building Welcoming Communities](https://opensource.guide/building-community/), or in [Best Practices for Maintainers](https://opensource.guide/best-practices/) 🤷‍♀
> 
> _Note:_ If maintainers find that their good first issues are not being surfaced, they can add the label "good first issue", "beginner friendly", or the like. If they have a similar label they are already using that is not being surfaced, they can contact us and we can add it to the list of synonymous labels. There can be a 24 hour lag for the data to refresh.
> 
> I am happy to help out on this in any way possible.
> 
> Thank you!

Duplicate of #

**Comment by forhad2001** [comment] 2019-09-10 17:35
[theme-check-master (1).zip](https://github.com/github/opensource.guide/files/3596997/theme-check-master.1.zip)

**Closed** 2019-09-26 14:53 UTC
