### ISSUE TITLE
Process for keeping translations up to date

### ISSUE THREAD

**Issue by katrinleinweber** [github/opensource.guide#1119] opened 2019-09-27 17:50 UTC
How about we collect some advice in [docs/translations.md](https://github.com/github/opensource.guide/blob/7b5aebc02a71b1f9f62873757a0643c0668612bd/docs/translations.md) under `Keeping translations up to date` or similar?

Working on #1118 I naively scrolled through the [commit list](https://github.com/github/opensource.guide/commits/master) and looked at merge commits that seemed to add content. Would `git diff $translation_branch master _articles/*.md` or similar be better?

**Comment by MikeMcQuaid** [comment] 2019-09-30 08:09
This seems like a good idea. Could you submit a PR with your recommended workflow?

**Comment by katrinleinweber** [comment] 2019-09-30 18:16
The snake seems to be eating its tail: [#1121/files#diff](https://github.com/github/opensource.guide/pull/1121/files#diff-31669052b00291ed5f9e4cd6db9fdd6bR31-R33) ;-)

I'll revisit this in a few days once there is a difference between my `translation_branch`& `upstream/master` to check whether the above initial idea is viable.

**Comment by syaifudin85** [comment] 2019-12-09 09:14
join

**Comment by katrinleinweber** [comment] 2019-12-15 14:23
This is a tough nut. I tried the following today:

1. Copy ID of last own commit in [_articles/de](https://github.com/github/opensource.guide/commits/master/_articles/de).
1. `git switch master && git pull upstream/master`
1. `git diff --word-diff $LAST_OWN upstream/master _articles/*.md > TODO-translate.txt`
1. `git switch $translation_branch`
1. `git rebase master`
1. Go through `TODO-translate.txt` & implement the English source's changes accordingly in the `_articles/**/*.md` translation(s). Because of the "own commit" step initially, one will sometimes notice already implemented changes by other translators. Skipping those seems less problematic, than remembering to only update the `translation_branch` _after_ `diff`ing.

**Comment by webknjaz** [comment] 2019-12-15 14:43
@katrinleinweber FWIW this is something I suggested a while back: https://github.com/github/opensource.guide/issues/288#issuecomment-283927635. It'd be nice to have it fully scripted so that it'd be easier to automatically check it...

**Comment by katrinleinweber** [comment] 2019-12-15 14:52
Yeah, that might be a more convenient source getting an ID for `3.`, but it would require each translation session to cover all of the English updates, wouldn't it?

Because those can occur in parallel to minor translation updates (correcting links, wording, or spelling), there is a risk of overlooking significant English updates that occured before such a minor update's SHA is recorded in the translation metadata, no?

**Comment by popcorner** [comment] 2019-12-17 09:46
What about considering using some professional translate tools instead of using Git directly?
Git is powerful but not the best tool for translating articles. Contributors have to use additional steps to check the difference, and it seems hard to automatically merge new contents into translation. And, The smallest unit of Git comparison is the lines, not sentences. These problems mean additional manual work.
But these professional translate tools like Transifex, Crowdin, and Weblate can do these things automatically, with lots of additional features. They can cut articles into sentences and track all the modifications of source articles. They can handle all the issues about translation from minor changes to new articles. Translators only need to translate all the sentences that marked as "need to be translated", and all the other things like generating the translation files can be done by the platform. And these tools can also help check the translation itself, like machine translation hints, word lists to keep the same word to have the same translation, and similarity check to help translators see the existing translation from these similar sentences and avoid duplicate work. These platforms can work with Git and commit changes, and all the other workflow won't be affected. These tools provide free services to open source projects, so maybe it's a good idea to consider using these platforms to make the translations easier to maintain.

**Comment by MikeMcQuaid** [comment] 2019-12-17 12:51
> What about considering using some professional translate tools instead of using Git directly?

This is being discussed in https://github.com/github/opensource.guide/issues/1133 and is on my list to investigate further (hopefully over Christmas).

**Comment by popcorner** [comment] 2019-12-18 08:46
@MikeMcQuaid That tool seems to be different from the platforms I suggested. GitLocalize looks like a lightweight translation tool working with Git, and what I suggested are professional translation platforms with lots of additional features. And these platforms are more famous (according to the number of search results) and their documents are better. 
For example, https://github.com/github/opensourcefriday are using Transifex. Maybe you can try to visit [their project](https://www.transifex.com/github-open-source/open-source-friday/dashboard/) and see which type of tool is more suitable for this repository.

**Comment by MikeMcQuaid** [comment] 2019-12-18 11:12
> For example, https://github.com/github/opensourcefriday are using Transifex. Maybe you can try to visit [their project](https://www.transifex.com/github-open-source/open-source-friday/dashboard/) and see which type of tool is more suitable for this repository.

I created the translation solution for both this project and Open Source Friday. The Transifex/Open Source Friday solution is unsuitable here as this repository is a Markdown document-based translation flow rather than lots of small strings.

https://github.com/github/opensource.guide/issues/1133 will be the next investigation and, if it seems an improvement on what we currently have, will be the next method of translation for this repository.

**Comment by foofaa222** [comment] 2020-04-27 15:04
👍🏼

**Comment by 137717unity** [comment] 2020-05-04 09:35
https://www.openarchives.org/rs/0.9.1/resourcesync

**Comment by smpbl** [comment] 2020-05-27 12:01
GOOD

**Comment by horace1981** [comment] 2020-05-27 22:43
Hi

**Comment by Jun6plushub** [comment] 2020-06-05 20:44
1119

**Comment by 666339** [comment] 2020-06-11 06:03
Hello

**Comment by bigwill1200** [comment] 2020-06-27 11:25
> How about we collect some advice in [docs/translations.md](https://github.com/github/opensource.guide/blob/7b5aebc02a71b1f9f62873757a0643c0668612bd/docs/translations.md) under `Keeping translations up to date` or similar?
> 
> Working on #1118 I naively scrolled through the [commit list](https://github.com/github/opensource.guide/commits/master) and looked at merge commits that seemed to add content. Would `git diff $translation_branch master _articles/*.md` or similar be better?

You are right

**Comment by bigwill1200** [comment] 2020-06-27 11:25
Yes

**Comment by TroySteven** [comment] 2020-06-28 23:20
gi

**Comment by AngelaMay27** [comment] 2020-07-07 13:39
> How about we collect some advice in [docs/translations.md](https://github.com/github/opensource.guide/blob/7b5aebc02a71b1f9f62873757a0643c0668612bd/docs/translations.md) under `Keeping translations up to date` or similar?
> 
> Working on #1118 I naively scrolled through the [commit list](https://github.com/github/opensource.guide/commits/master) and looked at merge commits that seemed to add content. Would `git diff $translation_branch master _articles/*.md` or similar be better?

**Comment by Jeedneux89** [comment] 2020-07-17 20:36
Nice

**Comment by marknguyen92** [comment] 2020-07-18 02:45
> How about we collect some advice in [docs/translations.md](https://github.com/github/opensource.guide/blob/7b5aebc02a71b1f9f62873757a0643c0668612bd/docs/translations.md) under `Keeping translations up to date` or similar?
> 
> Working on #1118 I naively scrolled through the [commit list](https://github.com/github/opensource.guide/commits/master) and looked at merge commits that seemed to add content. Would `git diff $translation_branch master _articles/*.md` or similar be better?

**Comment by jor514** [comment] 2020-08-17 05:22
yes

**Comment by jor514** [comment] 2020-08-17 05:22
yes

**Comment by jor514** [comment] 2020-08-17 05:22
yes

**Comment by kbptomo2020** [comment] 2020-08-20 04:51
mention: keithbrianptomo

**Comment by spiritualconnection3** [comment] 2020-08-26 08:42
The process for either has its own individual guidelines and or application
techniques that must be applied correctly to the the array as well as root
depending on if the code is consistantly progressing in transition vs
evelutionary progress used in patching older to newer.  In the event that
isn't possible, it may be that the solution may be more complicated than
needs to be. Try a simple fork patch. Basically apply a fork at the
transition. Let me know what you think and /or if it solves the glitch.
Hope that helpselps.

**Comment by hussenasseb** [comment] 2020-08-29 16:04
Stop

**Comment by devdev606** [comment] 2020-09-10 20:21
Hello world

**Comment by ding243** [comment] 2020-09-22 23:19
Hello world

**Comment by toomoon1979** [comment] 2020-09-23 04:55
Can you help me to watch iptv for word Chanel. If any one can get me how can download iptv m3u link Iam very thankful for get me that . 
Regarding your

**Comment by Paola954** [comment] 2020-09-24 07:08
https://github.com/github/opensource.guide/issues/1119#issuecomment-697133532

**Comment by ChenChunMing1986** [comment] 2020-10-02 16:00
> How about we collect some advice in [docs/translations.md](https://github.com/github/opensource.guide/blob/7b5aebc02a71b1f9f62873757a0643c0668612bd/docs/translations.md) under `Keeping translations up to date` or similar?
> 
> Working on #1118 I naively scrolled through the [commit list](https://github.com/github/opensource.guide/commits/master) and looked at merge commits that seemed to add content. Would `git diff $translation_branch master _articles/*.md` or similar be better?

**Comment by LeXTeR02** [comment] 2020-10-02 18:54
Verzonden vanaf mijn Huawei-telefoon-------- Oorspronkelijk bericht --------Van: toomoon1979 <notifications@github.com>Datum: wo 23 sep. 2020 06:56Aan: "github/opensource.guide" <opensource.guide@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Onderwerp: Re: [github/opensource.guide] Process for keeping translations up to date (#1119)
Can you help me to watch iptv for word Chanel. If any one can get me how can download iptv m3u link Iam very thankful for get me that .
Regarding yourDownload '' 'KODI' '' and install it then set upbit yhats need some thricks and knowledge,,, You cafind something like that on YouTube video's and try some channels,, i can promise you if its set-up correctly then ya have the best tv and cinema app of our round boll. Try some channels on YouTube, video's till you fond the set-up correct. If it wont work i know more apps for you.. contact me back. But try it,, its the best.  On KODI, really you have everything from past till far in the future REALLY. try and deffently METYou are receivingME KNOW this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mmoo301** [comment] 2020-10-08 10:37
#1741 #1119

**Comment by Alibhutta24** [comment] 2020-11-17 12:02
> This seems like a good idea. Could you submit a PR with your recommended workflow?

Quite

**Comment by Alibhutta24** [comment] 2020-11-17 12:03
> #1741 #1119

Quite

**Comment by Alibhutta24** [comment] 2020-11-17 12:03
> [#1119 (comment)](https://github.com/github/opensource.guide/issues/1119#issuecomment-697133532)

Quite

**Comment by Alibhutta24** [comment] 2020-11-17 12:03
> Can you help me to watch iptv for word Chanel. If any one can get me how can download iptv m3u link Iam very thankful for get me that .
> Regarding your

Quite

**Comment by Alibhutta24** [comment] 2020-11-17 12:04
> Hello world

Quite

**Comment by Alibhutta24** [comment] 2020-11-17 12:04
> > How about we collect some advice in [docs/translations.md](https://github.com/github/opensource.guide/blob/7b5aebc02a71b1f9f62873757a0643c0668612bd/docs/translations.md) under `Keeping translations up to date` or similar?
> > Working on #1118 I naively scrolled through the [commit list](https://github.com/github/opensource.guide/commits/master) and looked at merge commits that seemed to add content. Would `git diff $translation_branch master _articles/*.md` or similar be better?

Quiye

**Comment by Alibhutta24** [comment] 2020-11-17 12:04
Quite

**Comment by Alibhutta24** [comment] 2020-11-17 12:05
Close

**Comment by Alibhutta24** [comment] 2020-11-17 12:05
> How about we collect some advice in [docs/translations.md](https://github.com/github/opensource.guide/blob/7b5aebc02a71b1f9f62873757a0643c0668612bd/docs/translations.md) under `Keeping translations up to date` or similar?
> 
> Working on #1118 I naively scrolled through the [commit list](https://github.com/github/opensource.guide/commits/master) and looked at merge commits that seemed to add content. Would `git diff $translation_branch master _articles/*.md` or similar be better?

QUITE

**Comment by LoolliH** [comment] 2021-01-07 10:03
#2073

**Comment by LoolliH** [comment] 2021-01-07 10:04
هونكري نوديو

**Comment by LoolliH** [comment] 2021-01-07 10:04
تومر هيرا

**Comment by LoolliH** [comment] 2021-01-07 10:05
توربوني سودي

**Comment by LoolliH** [comment] 2021-01-07 10:05
اوي ناي

**Comment by LoolliH** [comment] 2021-01-07 10:05
انكاكوريرلي

**Comment by LoolliH** [comment] 2021-01-07 10:06
لي احد  كبير

**Comment by LoolliH** [comment] 2021-01-07 10:07
قريب

**Comment by abdullahkhan7127165** [comment] 2021-02-14 02:25
Duplicate of #

**Comment by MikeMcQuaid** [comment] 2021-03-10 12:14
Closing this out. I agree a process for this would be ideal but I don't think there's anything that we (GitHub) are planning on doing here in the near future. Would welcome a pull request for this, though.

**Closed by MikeMcQuaid** 2021-03-10 12:14 UTC
Labels: translation
