### ISSUE TITLE
404 Errors for two web fonts

### ISSUE THREAD

**Issue by theo-armour** [github/opensource.guide#336] opened 2017-02-28 07:35 UTC
Open developer console

go to: https://opensource.guide/

Note two identical error messages:

> Failed to load resource: the server responded with a status of 404 (Not Found)

for 

https://opensource.guide/static/fonts/roboto/roboto-regular.woff
https://opensource.guide/static/fonts/roboto/roboto-light.woff

**Comment by kytrinyx** [comment] 2017-02-28 17:54
When I look at the source for https://opensource.guide/ the reference that I see to the Roboto font is https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i which returns a 200 OK.

I'm on a Mac, and if I go to the Font Book and disable Roboto, then I am able to reproduce the 404 Not Found.

**Comment by kytrinyx** [comment] 2017-02-28 17:57
@sophshep would you take a look at this one?

**Comment by theo-armour** [comment] 2017-03-01 06:46
I am receiving the error on two W10 machines running Chrome.

Also one W10 machine running FF.

I am not able to reproduce the error on a Google Pixel Chromebook running a Chrome browser

**Comment by numrut** [comment] 2017-03-01 08:20
Error doesn't occurs if Roboto is installed on the system. Otherwise, Roboto is correctly included from Google Fonts but then its path is overwriten by the `/assets/css/index.css` file, which defines non-existent paths to font files. And initially it comes from the `/node_modules/primer-marketing-support/lib/fonts.scss` file.

So, we can either disable that file or just swap respective `link` tags in `/_includes/head.html` file (line 4 and 5).

**Comment by sophshep** [comment] 2017-03-01 14:28
I can take a look at this this week and fix. 

Pinging @github/design-systems which is the team responsible for Primer.

**Comment by sophshep** [comment] 2017-03-02 18:07
I have [a PR](https://github.com/github/github/pull/69565) open for a fix. Once it's published to the npm module, we'll be able to use it here.

**Comment by muan** [comment] 2017-03-13 18:43
@sophshep looks like it's all merged in and published?

**Comment by broccolini** [comment] 2017-04-08 00:53
Heads up the module changes _are_ published but I haven't cut a new release of the meta-packages (such as `primer-marketing` or `primer-css`) yet because there is a problem with another module. Working on a fix, and may not affect this site if you reference the specific `primer-marketing-support` version, `0.5.0`.

**Comment by bkeepers** [comment] 2017-04-08 02:02
Thanks @broccolini

**Comment by broccolini** [comment] 2017-04-11 23:10
@bkeepers This fixed is published, you'll need to bump to the latest version to get the fix on the the open source site: https://www.npmjs.com/package/primer-marketing - ping us if you hit any issues. cc @sophshep

**Comment by nayafia** [comment] 2017-06-12 14:07
@bkeepers are you able to update versions so we can close this out? (This was on my SEO todo list too)

**Comment by bkeepers** [comment] 2017-06-27 13:39
@nayafia Looks like @sophshep is taking care of this in #404

**Comment by nayafia** [comment] 2017-07-24 18:16
Think we can close this now that #404 has been merged :party:

**Closed by nayafia** 2017-07-24 18:16 UTC
